# DEEPSORT:
#   MODEL_TYPE: "osnet_x_25"
#   MAX_DIST: 0.3 # The matching threshold. Samples with larger distance are considered an invalid match
#   MAX_IOU_DISTANCE: 0.6 # Gating threshold. Associations with cost larger than this value are disregarded.
#   MAX_AGE: 30 # Maximum number of missed misses before a track is deleted
#   N_INIT: 3 # Number of frames that a track remains in initialization phase
#   NN_BUDGET: 70 # Maximum size of the appearance descriptors gallery
  
DEEPSORT:
  MODEL_TYPE: "osnet_x_25"
  MAX_DIST: 0.8 # The matching threshold. Samples with larger distance are considered an invalid match
  MAX_IOU_DISTANCE: 0.5 # Gating threshold. Associations with cost larger than this value are disregarded.
  MAX_AGE: 100 # Maximum number of missed misses before a track is deleted
  N_INIT: 1 # Number of frames that a track remains in initialization phase
  NN_BUDGET: 150 # Maximum size of the appearance descriptors gallery
  # MIN_CONFIDENCE: 0.15
  # NMS_MAX_OVERLAP: 0.15
  


